gui:
  nerdFontsVersion: "3"

git:
  overrideGpg: true

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: 'D'
    command: >-
      git push {{ .SelectedLocalBranch.UpstreamRemote }} --delete {{ .SelectedLocalBranch.UpstreamBranch }} &&
      git branch -D {{ .SelectedLocalBranch.Name }}
    description: "delete local AND remote branch"
    context: 'localBranches'
    output: log
  - key: 'T'
    command: >-
      git for-each-ref --format='%(refname:short) %(symref)' refs/remotes/ | \
      while read -r remote_branch symref; do
          # Skip symbolic refs like 'origin/HEAD'
          [ -n "$symref" ] && continue

          # Strip 'origin/' (or other remote name) up to the first slash
          local_name="${remote_branch#*/}"

          # Track the branch if it doesn't exist locally yet
          if ! git show-ref --verify --quiet "refs/heads/$local_name"; then
              git branch --track "$local_name" "$remote_branch"
          fi
      done
    description: "add ALL remote branches to the list"
    context: 'localBranches'
    output: log
