gui:
  nerdFontsVersion: "3"

git:
  overrideGpg: true

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: 'D'
    command: >-
      git push {{ .SelectedLocalBranch.UpstreamRemote }} --delete {{ .SelectedLocalBranch.UpstreamBranch }} &&
      git branch -D {{ .SelectedLocalBranch.Name }}
    description: "delete local AND remote branch"
    context: 'localBranches'
    stream: true
  - key: 'T'
    command: >-
      for branch in $(git branch --all | grep '^\s*remotes' | egrep --invert-match '(:?HEAD|master)$'); do     git branch --track "${branch##*/}" "$branch"; done
    description: "add ALL remote branches to the list"
    context: 'localBranches'
    stream: true
