name: Build Images
on:
  push:
    branches: [ "main", "rewrite" ]

jobs:
  build:
    name: Build ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          # maybe in the future, but without kvm there is no reason to try
          # - system: aarch64-linux 
          #   os: ubuntu-24.04-arm
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Maximize Disk Space
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build All Images
        run: |
          # 1. Build using software emulation
          nix build .#images.${{ matrix.system }}.all \
            --option system-features "nixos-test benchmark big-parallel kvm" \
            --option auto-optimise-store true

          mkdir -p dist
          
          find -L result -type f | while read -r file; do
            filename=$(basename "$file")
            cp -L "$file" "dist/${{ github.ref_name }}-${{ matrix.system }}-$filename"
          done

          # 3. Reclaim space immediately
          rm result
          nix-store --gc

      - name: Create Versioned Release (Pinned)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}-${{ github.sha }}
          name: "${{ github.ref_name }} @ ${{ github.sha }}"
          files: versioned-dist/*
          prerelease: true

      - name: Update Rolling Release (Latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-${{ github.ref_name }}
          name: "Latest ${{ github.ref_name }} Bootstrap"
          files: rolling-dist/**
          prerelease: true
